

logging:
  level:
    com.qn.web.house.mapper: DEBUG
    com.qn.web.login.mapper: DEBUG


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html


mybatis:
  type-aliases-package: com.qn.web.entity
  mapperLocations: classpath:mapper/*/*.xml


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mapper:
  mappers: com.qn.web.common.CurdMapper
  identity: MYSQL


server:
  port: 8081
